set_property PACKAGE_PIN A3 [get_ports {R_s[0]}]
set_property PACKAGE_PIN B4 [get_ports {R_s[1]}]
set_property PACKAGE_PIN C5 [get_ports {R_s[2]}]
set_property PACKAGE_PIN A4 [get_ports {R_s[3]}]

set_property PACKAGE_PIN C6 [get_ports {G_s[0]}]
set_property PACKAGE_PIN A5 [get_ports {G_s[1]}]
set_property PACKAGE_PIN B6 [get_ports {G_s[2]}]
set_property PACKAGE_PIN A6 [get_ports {G_s[3]}]

set_property PACKAGE_PIN B7 [get_ports {B_s[0]}]
set_property PACKAGE_PIN C7 [get_ports {B_s[1]}]
set_property PACKAGE_PIN D7 [get_ports {B_s[2]}]
set_property PACKAGE_PIN D8 [get_ports {B_s[3]}]

set_property PACKAGE_PIN B12 [get_ports Vsync]
set_property PACKAGE_PIN B11 [get_ports Hsync]

set_property PACKAGE_PIN E3 [get_ports CLK_100MHz]

set_property PACKAGE_PIN H15 [get_ports {led[7]}]
set_property PACKAGE_PIN L18 [get_ports {led[6]}]
set_property PACKAGE_PIN T11 [get_ports {led[5]}]
set_property PACKAGE_PIN P15 [get_ports {led[4]}]
set_property PACKAGE_PIN K13 [get_ports {led[3]}]
set_property PACKAGE_PIN K16 [get_ports {led[2]}]
set_property PACKAGE_PIN R10 [get_ports {led[1]}]
set_property PACKAGE_PIN T10 [get_ports {led[0]}]

set_property PACKAGE_PIN U13 [get_ports {anode[7]}]
set_property PACKAGE_PIN K2 [get_ports {anode[6]}]
set_property PACKAGE_PIN T14 [get_ports {anode[5]}]
set_property PACKAGE_PIN P14 [get_ports {anode[4]}]
set_property PACKAGE_PIN J14 [get_ports {anode[3]}]
set_property PACKAGE_PIN T9 [get_ports {anode[2]}]
set_property PACKAGE_PIN J18 [get_ports {anode[1]}]
set_property PACKAGE_PIN J17 [get_ports {anode[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {anode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]

# JB higher socket
set_property PACKAGE_PIN H14 [get_ports get_bluetooth]

set_property PACKAGE_PIN J15 [get_ports RST_n]
set_property PACKAGE_PIN L16 [get_ports error_note]


set_property PACKAGE_PIN M18 [get_ports BTN_U]
set_property PACKAGE_PIN P18 [get_ports BTN_D]
set_property PACKAGE_PIN P17 [get_ports BTN_L]
set_property PACKAGE_PIN M17 [get_ports BTN_R]
set_property PACKAGE_PIN N17 [get_ports BTN_C]

set_property IOSTANDARD LVCMOS33 [get_ports {R_s[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_s[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_s[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_s[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_s[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_s[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_s[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_s[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_s[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_s[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_s[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_s[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports Hsync]
set_property IOSTANDARD LVCMOS33 [get_ports Vsync]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports get_bluetooth]
set_property IOSTANDARD LVCMOS33 [get_ports RST_n]
set_property IOSTANDARD LVCMOS33 [get_ports BTN_U]
set_property IOSTANDARD LVCMOS33 [get_ports BTN_D]
set_property IOSTANDARD LVCMOS33 [get_ports BTN_L]
set_property IOSTANDARD LVCMOS33 [get_ports BTN_R]
set_property IOSTANDARD LVCMOS33 [get_ports BTN_C]
set_property IOSTANDARD LVCMOS33 [get_ports error_note]

set_property IOSTANDARD LVCMOS33 [get_ports {test_cur[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_cur[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_cur[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_cur[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_map[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_map[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_map[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_map[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_mask[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_mask[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_mask[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_mask[0]}]
set_property PACKAGE_PIN U16 [get_ports {test_cur[3]}]
set_property PACKAGE_PIN U17 [get_ports {test_cur[2]}]
set_property PACKAGE_PIN V17 [get_ports {test_cur[1]}]
set_property PACKAGE_PIN R18 [get_ports {test_cur[0]}]
set_property PACKAGE_PIN V11 [get_ports {test_map[3]}]
set_property PACKAGE_PIN V12 [get_ports {test_map[2]}]
set_property PACKAGE_PIN V14 [get_ports {test_map[1]}]
set_property PACKAGE_PIN V15 [get_ports {test_map[0]}]
set_property PACKAGE_PIN T16 [get_ports {test_mask[3]}]
set_property PACKAGE_PIN U14 [get_ports {test_mask[2]}]
set_property PACKAGE_PIN T15 [get_ports {test_mask[1]}]
set_property PACKAGE_PIN V16 [get_ports {test_mask[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports inited]
set_property PACKAGE_PIN H17 [get_ports inited]
